# Generated by Django 2.2.9 on 2020-02-18 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Первая Категория',
                'verbose_name_plural': 'Первая категория',
            },
        ),
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('lol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tgbot.Arrr', verbose_name='категория1')),
            ],
            options={
                'verbose_name': 'Вторая Категория',
                'verbose_name_plural': 'Вторая категория',
            },
        ),
        migrations.CreateModel(
            name='Meni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('structure', models.CharField(blank=True, max_length=250, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='вес в гр.')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='цена')),
                ('lol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tgbot.Category1', verbose_name='категория2')),
            ],
            options={
                'verbose_name': 'ТОвар',
                'verbose_name_plural': 'все товары',
            },
        ),
    ]
