# Generated by Django 2.2.9 on 2020-03-22 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название кухни')),
                ('unic', models.CharField(blank=True, db_index=True, max_length=250, null=True, unique=True, verbose_name='Уникальное наименование')),
            ],
            options={
                'verbose_name': 'Первая Категория',
                'verbose_name_plural': 'Первая категория',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField(unique=True, verbose_name='id_пользователя')),
                ('nickname', models.CharField(max_length=100, verbose_name='има пользователя')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('delivery', models.CharField(default='🚗 Привезти', max_length=15, verbose_name='Тип доставки')),
                ('time_delivery', models.CharField(default='Как можно скорее', max_length=20, verbose_name='Время доставки')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время заказа')),
                ('amount_to_pay', models.PositiveIntegerField(verbose_name='Сумма в ₽')),
                ('type_delivery', models.CharField(max_length=15, verbose_name='Тип доставки')),
                ('address_delivery', models.CharField(max_length=100, null=True, verbose_name='Адрес доставки')),
                ('time_delivery', models.CharField(max_length=50, verbose_name='Время доставки')),
                ('food', models.TextField(verbose_name='Позиции')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.Users', verbose_name='Заказ пользователя')),
            ],
            options={
                'verbose_name': 'Заказы ',
                'verbose_name_plural': 'Заказы пользователей',
            },
        ),
        migrations.CreateModel(
            name='CategoryTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование раздела')),
                ('unic', models.CharField(blank=True, db_index=True, max_length=250, null=True, unique=True, verbose_name='Уникальное наименование')),
                ('category_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tgbot.CategoryOne', verbose_name='Категория-1')),
            ],
            options={
                'verbose_name': 'Вторая Категория',
                'verbose_name_plural': 'Вторая категория',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=250, null=True)),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('name_product', models.CharField(max_length=250, verbose_name='Наименование товара')),
                ('photo', models.URLField(verbose_name='URL фото продукта')),
                ('weight', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Вес в гр.')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Цена')),
                ('baskUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.Users', verbose_name='Продукт пользователя')),
            ],
            options={
                'verbose_name': 'Корзина пользователя',
                'verbose_name_plural': 'Корзина пользователей',
            },
        ),
        migrations.CreateModel(
            name='AllMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название товара')),
                ('unic', models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Уникальное наименование')),
                ('structure', models.CharField(blank=True, max_length=250, null=True, verbose_name='Состав')),
                ('photo', models.URLField(blank=True, null=True, verbose_name='URL фото продукта')),
                ('weight', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='Вес в гр.')),
                ('price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='Цена')),
                ('category_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tgbot.CategoryTwo', verbose_name='Категория-2')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Все товары',
            },
        ),
    ]
