# Generated by Django 2.2.9 on 2020-03-31 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryone',
            options={'verbose_name': 'Первая категория', 'verbose_name_plural': 'Первая категория'},
        ),
        migrations.AlterModelOptions(
            name='categorytwo',
            options={'verbose_name': 'Вторая категория', 'verbose_name_plural': 'Вторая категория'},
        ),
        migrations.RemoveField(
            model_name='allmenu',
            name='unic',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='categoryone',
            name='unic',
        ),
        migrations.RemoveField(
            model_name='categorytwo',
            name='unic',
        ),
        migrations.AddField(
            model_name='allmenu',
            name='volume',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество в шт'),
        ),
        migrations.AlterField(
            model_name='allmenu',
            name='category_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.CategoryTwo', verbose_name='Категория-2'),
        ),
        migrations.AlterField(
            model_name='allmenu',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='allmenu',
            name='structure',
            field=models.CharField(max_length=250, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='product_id',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
    ]
