# Generated by Django 2.2.9 on 2020-02-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_arrr_unic'),
    ]

    operations = [
        migrations.AddField(
            model_name='category1',
            name='unicс',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
