# Generated by Django 2.2.9 on 2020-04-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_users_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='basket_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
