# Generated by Django 2.2.9 on 2020-02-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_category1_unicс'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meni',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
