# Generated by Django 2.2.9 on 2020-02-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_auto_20200222_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='meni',
            name='unic',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
