# Generated by Django 2.2.9 on 2020-04-27 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_users_basket_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmenu',
            name='category_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tgbot.CategoryOne', verbose_name='Категория-1'),
        ),
        migrations.AlterField(
            model_name='allmenu',
            name='category_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tgbot.CategoryTwo', verbose_name='Категория-2'),
        ),
        migrations.AlterField(
            model_name='allmenu',
            name='volume',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество-шт(Пицца-см)'),
        ),
    ]
