# Generated by Django 2.2.9 on 2020-05-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_auto_20200501_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_sum', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Минимальная сумма заказа в ₽')),
                ('channel_orders', models.CharField(default='не указан', max_length=30, verbose_name='название канала для приема заказов')),
                ('channel_help', models.CharField(default='не указан', max_length=30, verbose_name='название канала для обратной связи')),
                ('id_channel_orders', models.CharField(default='нет', max_length=20, verbose_name='Id канала для приема заказов')),
                ('id_channel_help', models.CharField(default='нет', max_length=20, verbose_name='Id канала для обратной связи')),
                ('news', models.TextField()),
            ],
            options={
                'verbose_name': 'Конфигурации бота',
                'verbose_name_plural': 'Конфигурации бота',
            },
        ),
    ]
