# Generated by Django 2.2.9 on 2020-02-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_basket_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Карзина пользователя', 'verbose_name_plural': 'Карзина пользователей'},
        ),
        migrations.AddField(
            model_name='basket',
            name='name_product',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='basket',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='вес в гр.'),
        ),
    ]
