# Generated by Django 2.2.9 on 2020-05-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='news',
            field=models.TextField(blank=True, null=True),
        ),
    ]
