# Generated by Django 2.2.9 on 2020-05-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_auto_20200504_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(default='1', max_length=5),
        ),
    ]
