# Generated by Django 2.2.9 on 2020-03-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0009_users_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='time_delivery',
            field=models.CharField(default='Как можно скорее', max_length=20, verbose_name='время доставки'),
        ),
    ]
