# Generated by Django 2.2.9 on 2020-03-11 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0010_users_time_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('amount_to_pay', models.PositiveIntegerField()),
                ('type_delivery', models.CharField(max_length=15, verbose_name='тип доставки')),
                ('address_delivery', models.CharField(max_length=100)),
                ('food', models.TextField()),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.Users', verbose_name='продукт юзера')),
            ],
        ),
    ]
