# Generated by Django 2.2.9 on 2020-03-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0011_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='time_delivery',
            field=models.CharField(default=23, max_length=50),
            preserve_default=False,
        ),
    ]
