# Generated by Django 2.2.9 on 2020-03-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0012_orders_time_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meni',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Все товары'},
        ),
        migrations.AlterField(
            model_name='arrr',
            name='unic',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category1',
            name='unicс',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='meni',
            name='unic',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='има пользователя'),
        ),
    ]
