# Generated by Django 2.2.9 on 2020-03-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0013_auto_20200315_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meni',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='meni',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='вес в гр.'),
        ),
    ]
